### ISSUE TITLE
F-Droid scanner - DEBUG: Problem: found class 'com/google/ads/interactivemedia/v3/api/AdEvent'

### ISSUE THREAD

**Issue by licaon-kter** [Infomaniak/android-infomaniak-meet#1]
I guess it comes via https://github.com/jitsi/jitsi-meet/blob/android-sdk-8.6.0/package.json#L105 -> https://github.com/react-native-video/react-native-video/blob/v6.0.0-alpha.7/android/build.gradle#L75-L77

**Comment by JorisBodin** [comment]
It must be the same problem for the other fdroid apps that use this sdk, right?

**Comment by licaon-kter** [comment]
https://github.com/podverse/podverse-rn/issues/2133 so far too

**Comment by licaon-kter** [comment]
Cleared as stubs 🎉
